using System;
using System.Collections.Generic;

namespace Cascade.Agents
{
    public enum LongTermGoalType { None, FindPerson }

    [Serializable]
    public sealed class InitialRelationship
    {
        public string TargetName;
        public RelationshipKind Kind;
        public float Trust;
        public float Affection;
    }

    /// <summary>
    /// Everything that defines an agent before the simulation starts. Hand-authored, sampled from an archetype, or
    /// generated by Claude at edit time (then validated). Names are resolved to entity ids by the spawner.
    /// </summary>
    [Serializable]
    public sealed class AgentProfile
    {
        public string Name = "NPC";
        public string Archetype = "Average";
        public Personality Personality = new Personality();
        public string Background = "";
        public string SpeechStyle = "";
        public bool KnowsAllExits;
        public LongTermGoalType LongTermGoal;
        public string LongTermTargetName;
        public List<InitialRelationship> Relationships = new List<InitialRelationship>();
        public float InitialHealth = 1f;
    }
}
